### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by zh794390558**
support for gcc4.8

### CODE REVIEW

**Comment by danpovey** [comment]
What error does this fix?

**Comment by zh794390558** [comment]
I can not compile this under CentOS with gcc 4.8.

**Comment by danpovey** [comment]
So what is the error message?

**Comment by zh794390558** [comment]
just this
```
In file included from /usr/include/c++/4.8.2/unordered_map:35:0,
                 from kaldi_lm.h:9,
                 from discount_ngrams.cc:1:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from discount_ngrams.cc:1:0:
kaldi_lm.h:10:12: error: ‘std::unordered_map’ has not been declared
 using std::unordered_map;
            ^
kaldi_lm.h:63:3: error: ‘unordered_map’ does not name a type
   unordered_map<string, double> counts; // map from "predicted" to count.
   ^
```

**Comment by danpovey** [comment]
OK, can you please just add a comment above that line you changed, saying
```
 # the -std=c++11 flag is just needed to support gcc 4.8, in which std::unordered_map
 # requires C++11 support.
```

**Comment by danpovey** [comment]
thanks, I fixed this in #2.

**Pull request closed without merging**
